const ERROR_CODES = {
    AUTH_ERROR: 'AUTH_ERROR',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    SERVER_ERROR: 'SERVER_ERROR',
    PAYMENT_ERROR: 'PAYMENT_ERROR',
};
module.exports = ERROR_CODES;