module.exports = {
  admin: [
    "admins",
    "admin_roles",
    "admin_permissions",
    "admin_role_permissions",
    "admin_logs",
  ],
  ecommerce: [
    "categories",
    "product_categories",
    "products",
    "product_images",
    "product_promotions",
    "usuarios",
    "enderecos_usuario",
    "payment_methods",
    "cupons",
    "favorites",
    "carrinhos",
    "carrinho_itens",
    "carrinhos_abandonados",
    "carrinhos_abandonados_notifications",
    "pedidos",
    "pedidos_produtos",
    "produto_avaliacoes",
  ],
  services: [
    "colaboradores",
    "colaborador_images",
    "especialidades",
    "solicitacoes_servico",
    "avaliacoes_servico",
    "comunicacoes_enviadas",
  ],
  drones: [
    "drone_models",
    "drone_gallery_items",
    "drone_model_media_selections",
    "drone_page_settings",
    "drone_representatives",
    "drone_comments",
    "drone_comment_media",
  ],
  news: [
    "news_posts",
    "news_clima",
    "news_cotacoes",
    "news_cotacoes_history",
  ],
  shipping: [
    "shipping_zones",
    "shipping_zone_cities",
    "shipping_rates",
  ],
  settings: [
    "shop_settings",
    "site_hero_settings",
    "password_reset_tokens",
  ],
};