apiVersion: v1
kind: Secret
metadata:
  name: kavita-backend-secrets
type: Opaque
stringData:
  DB_USER: kavita
  DB_PASSWORD: super-secret-password
  AWS_ACCESS_KEY_ID: YOUR_KEY
  AWS_SECRET_ACCESS_KEY: YOUR_SECRET
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: your-bucket
  STORAGE_CDN_URL: https://cdn.example.com
